# This file is covered by the LICENSE file in the root of this project.
# Developed by: Xieyuanli Chen
# Configuration for preparing residual images (specifying all the paths)
# --------------------------------------------------------------------

# General parameters
# number of frames for training, -1 uses all frames
num_frames: -1
# plot images
debug: False
# normalize/scale the difference with corresponding range value
normalize: True
# use the last n frame to calculate the difference image
num_last_n: 8

# Inputs
# the folder of raw LiDAR scans
scan_folder: '/data1/MotionSeg3d_Dataset/data_odometry_velodyne/dataset/'
# ground truth poses file
pose_file: '/data1/MotionSeg3d_Dataset/data_odometry_velodyne/dataset/'
# calibration file
calib_file: '/data1/MotionSeg3d_Dataset/data_odometry_velodyne/dataset/'

# Outputs
# the suffix should be the same as num_last_n!
residual_image_folder: '/data-ssd/data5/cxm/MOS/temp_data/multirange2/'
visualize: True
visualization_folder: '/data-ssd/data5/cxm/MOS/temp_data/multirange2/visualization-range/'

# range image parameters
range_image:
  height: 64
  width: 2048
  fov_up: 3.0
  fov_down: -25.0
  max_range: 50.15
  min_range: 1.85

