###################
## Model options
model_params:
  grid_size:
    - 480
    - 360
    - 32

  fea_dim: 9
  ppmodel_init_dim: 32
  use_norm: True
  dropout: 0.5  # 0.2
  circular_padding: True

###################
## Data_loader options
data_loader:
  data_path: "/data1/MotionSeg3d_Dataset/data_odometry_velodyne/dataset/" # "/home/cooper/data-ssd/data5/cqy/custom_dataset/32line_remove_nan/" # "/data1/MotionSeg3d_Dataset/data_odometry_velodyne/dataset/"
  data_path_test:  "/data1/MotionSeg3d_Dataset/data_odometry_velodyne/dataset/test/"
  return_ref: True  # reflectivity(intensity)
  residual: 8  # residual 1-8, 0 for none
  residual_path: "/data-ssd/data5/cxm/MOS/KITTI_polar_range_resdata/"
  batch_size: 6
  shuffle: True
  drop_few_static_frames: True  # drop_few_static_frames for training, speed up training while slightly reduce the accuracy
  num_workers: 4  # Set to four times the number of available GPUs

  ignore_label: 255
  fixed_volume_space: True

  rotate_aug: True
  flip_aug: True
  transform_aug: True

###################
## model infer 
model_load_path: "/data-ssd/data5/cxm/MOS/BEV-MF-PR/model_save_dir/2024-6-01-00:44-BEV-MF/best_moving_miou/BEV-MF-95-84.45.pt"
val: True # False
test: False # True # True False
